/*
 * Copyright (c) Estonian Information System Authority
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

export default interface AuthenticateOptions {
  /**
   * Authentication challenge GET request URL
   *
   * This URL should respond to a GET request with a cryptographic nonce.
   * The request will be made by the browser extension. The extension will
   * use this nonce to generate an authentication token.
   *
   * @example
   *   // Example response from the server
   *   {"nonce": "<nonce>"}
   */
  getAuthChallengeUrl: string;

  /**
   * Authentication token POST request URL
   *
   * This URL should accept a JSON payload via a POST request which contains
   * the authentication token generated by the browser extension.
   *
   * After the server validates the token,the server should respond
   * with a 2xx status code and an optional JSON payload.
   *
   * If the provided token was invalid or the user should be forbidden access
   * for a different reason, the server should respond with an appropriate
   * HTTP error status code and an optional JSON payload.
   *
   * The authenticate method will resolve or reject with
   * the optional JSON payload if the server chooses to provide it.
   *
   * @example
   *   // Example request payload
   *   {"token": "<base64 openid-x509 token JWT>"}
   */
  postAuthTokenUrl: string;

  /**
   * Authentication success GET request URL
   *
   * This URL should accept a GET request which contains the headers set in the headers object.
   *
   * If backend has received the valid authentication token from the Android authentication app, successful login web-
   * page should be returned.
   *
   * If the token was not received by the backend or if the token was invalid, the server should respond with an
   * appropriate HTTP error status code and an optional JSON payload.
   */
  getAuthSuccessUrl?: string;

  /**
   * Boolean to decide which application to use for the authentication request.
   *
   * If true, the request will be sent to the Android authentication app
   * https://github.com/TanelOrumaa/Estonian-ID-card-mobile-authenticator-POC/tree/main/MobileAuthApp
   *
   * If false, the request will be sent to the browser plugin (to use with ID-card reader).
   *
   * If not specified, false is assumed.
   */
  useAuthApp?: boolean;

  /**
   * String value which can be displayed to the user in the Android authentication app. If not specified, nothing will
   * be displayed.
   */
  applicationName?: string;

  /**
   * Headers to append to the requests.
   */
  headers?: {
    [key: string]: string;
  };

  /**
   * Time in milliseconds before a user interaction, for example PIN entry, times out.
   *
   * When not specified, defaults to 2 minutes.
   */
  userInteractionTimeout?: number;

  /**
   * Time in milliseconds before a server request, for example auth challenge request, times out.
   *
   * When not specified, defaults to 20 seconds.
   */
  serverRequestTimeout?: number;

  /**
   * A two-letter ISO 639-1 language code.
   *
   * If translations exist for the given language, then the user interface will be displayed in this language.
   */
  lang?: string;
}
